### ISSUE TITLE
Core Gameplay: Items

### ISSUE THREAD

**Issue by rsandor** [NesHacker/LabyrinthOfTheDragon#5]
## Gameplay Description

- There are 8 types of consumable items in the game:
- Common: potion (heals HP), ether (heals MP/SP), remedy (status effect cure-all)
- Uncommon: Attack Up, Defense Up, Elixer (heals HP + MP)
- Rare: Regen Potion, Haste Potion
- Each item also has a power tier (e.g. S-Rank Regen, C-Rank Elixer, etc.) that determine usage power
- The player's inventory has slots for each item type and tier (8 x 4 = 32 slots total)
- The player can only use items in battle

## Todo List

- [x] Item definition, code, and instancing module
- [x] Player inventory
- [x] Use items in battle

**Comment by ChestnutDev** [comment]
Just curious: Is `Elixer` intentionally spelled that way? I usually know it as `Elixir`, but just wanted to bring it up in case it's a typo.
